### ISSUE TITLE
Automate publishing of blog

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/blog#102]
Use GitHub Actions to automatically publish the blog website when a pull request is merged or a commit is pushed to the live branch

**Comment by practicalli-john** [comment]
Create a GitHub action to build and publish the blog site to GitHub pages branch in the same repository

```
name: Publish Blog
on:
  push:
    branches:
    - live

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.855

      - name: Build Blog site
        run: clojure -M:build

      - name: Publish to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.PRACTICALLI_BLOG_PUBLISH_TOKEN }}  # -> remember add this in settings/secrets
          branch: gh-pages # The branch the action should deploy to.
          folder: public/blog # The folder the action should deploy.
          commit-message: ${{ github.event.head_commit.message }}
          single-commit: yes
```
